name: charge_route
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  intl: ^0.19.0
  google_fonts: 6.1.0
  bloc: ^8.1.4
  font_awesome_flutter: ^10.7.0
  salomon_bottom_bar: ^3.3.2
  location: ^6.0.1
  flutter_polyline_points: ^2.0.0
  google_maps_flutter: ^2.5.3
  dio: ^5.4.3+1
  go_router: ^14.0.2
  shared_preferences: ^2.3.2
  flutter_dotenv: ^5.1.0
  geolocator: ^13.0.1
  flutter_typeahead: ^5.2.0
  http: ^1.2.2
  dotenv: ^4.2.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  freezed: ^2.5.7
  get_it: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: ^9.1.4
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - .env
